#cloud-config
#
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJeNynN0jAeTRo7LJKt2Ln28WgERMEtZZjPhTIZYRd/C/Ng3IH7KZYICby6RnY9p4mS6LUD7BbdYNN4XTgvbofwO+aRM9LFVK7AXNqj4xW9dMz41OU7qN45ilZNyGRJ7hTVLso7t68cP5qPiXP3DBBVjzDItp4LcgoDIdvCGw7b3jcuPtzhB0P8rwo2V1gt0FsYc58ubf1QUqcAgNsUsN6K1R+4JnTfIIw/GYZvV4vwKOXnMmNx2WxvLNfLHBiMCneg25tq24SbMsDMARO67vg4brM9jlgx28z23PlKG/YkEjQ0HhR0PyV2uNLnXF426b2Megu8ccvcZ8VUIP6vpl4VxLwXaCVO+BhdIA2gcvUO5epWzQSj7/g9MjS5lqta6MgHZgmc7hVEZFoGIfQW8IWrcFlTElw0HeEWKQ5/lWZ36Bs/3MGcsyqzfumVgNJ+p7wrUUhJ/4POVTPsWopjBTV6Vp442xuUABU9uJ8ZXipYjb80hyAzc8zNLWoWPNpLXU= slava@debwork"

package_update: true

packages:
  - mongodb
  - ruby-full
  - ruby-bundler
  - build-essential
  - git

runcmd:
  - sudo systemctl start mongodb
  - sudo systemctl enable mongodb
  - cd /home/yc-user
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd reddit && bundle install
  - puma -d
